// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWatchList.Data;

#nullable disable

namespace MyWatchList.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250507172833_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyWatchList.Models.WatchItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WatchDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WatchItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A mind-bending thriller",
                            IsWatched = true,
                            Title = "Inception",
                            Type = "Movie",
                            WatchDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "A chemistry teacher turns to crime",
                            IsWatched = true,
                            Title = "Breaking Bad",
                            Type = "Series",
                            WatchDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "What is real?",
                            IsWatched = false,
                            Title = "The Matrix",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sci-fi mystery",
                            IsWatched = false,
                            Title = "Stranger Things",
                            Type = "Series"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Classic mafia drama",
                            IsWatched = true,
                            Title = "The Godfather",
                            Type = "Movie",
                            WatchDate = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Space and time travel",
                            IsWatched = false,
                            Title = "Interstellar",
                            Type = "Movie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
